import React from "react";

import "../css/Admin_report.css";

const reports = [
  {
    date: "20 May 2026",
    type: "Weekly Report",
    generatedBy: "Admin",
    status: "Completed",
  },
  {
    date: "18 May 2026",
    type: "Monthly Report",
    generatedBy: "System",
    status: "Pending",
  },
  {
    date: "15 May 2026",
    type: "Attendance Report",
    generatedBy: "Admin",
    status: "Completed",
  },
];

function Admin_Reports() {
  return (
    <div className="reports">

      {/* Header */}

      <div className="reports_header">

        <h1>Reports</h1>

      </div>

      {/* Report Types */}

      <div className="report_cards">

        <div className="report_card">
          <h3>Weekly Report</h3>

          <button>Download PDF</button>
        </div>

        <div className="report_card">
          <h3>Monthly Report</h3>

          <button>Export CSV</button>
        </div>

        <div className="report_card">
          <h3>AI Summary Report</h3>

          <button>View Report</button>
        </div>

        <div className="report_card">
          <h3>Attendance Report</h3>

          <button>Download PDF</button>
        </div>

      </div>

      {/* Table */}

      <div className="reports_table">

        <table>

          <thead>

            <tr>

              <th>Date</th>
              <th>Report Type</th>
              <th>Generated By</th>
              <th>Status</th>
              <th>Download</th>

            </tr>

          </thead>

          <tbody>

            {reports.map((report, index) => (

              <tr key={index}>

                <td>{report.date}</td>

                <td>{report.type}</td>

                <td>{report.generatedBy}</td>

                <td>

                  <span
                    className={
                      report.status === "Completed"
                        ? "completed"
                        : "pending"
                    }
                  >
                    {report.status}
                  </span>

                </td>

                <td>

                  <div className="report_actions">

                    <button>
                      PDF
                    </button>

                    <button>
                      CSV
                    </button>

                    <button>
                      View
                    </button>

                  </div>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>

    </div>
  );
}

export default Admin_Reports;